import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const roboto = Roboto({
  weight: ["100", "400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased flex flex-col min-h-screen`}
      >
        <div className="flex flex-col justify-between min-h-screen">
          <NavBar />

          <main className="flex-grow px-4">{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
